language: erlang

otp_release:
  - 23.0
  - 24.2
  - 25.0

env:
  - COUCHDB_BRANCH=82-rebar3

sudo: false

addons:
  apt:
    update: true
    packages:
      - libmozjs185-dev

before_install:
  - sudo apt-get install -y curl python
  - git clone --no-single-branch --depth 1 https://github.com/jiahuili430/couchdb.git


before_script:
  - cd couchdb
  - git checkout origin/${COUCHDB_BRANCH}
  - ./configure --disable-docs --disable-fauxton
  - cp -r ../!(couchdb) ./apps/config
  - make

script:
  - make eunit apps=config

cache: apt
