language: erlang

otp_release:
  - 21.1
  - 20.3
  - 19.3

sudo: false

addons:
  apt:
    packages:
      - libmozjs185-dev

before_install:
  - apt-get update && apt-get install -y curl python
  - curl -sO https://www.foundationdb.org/downloads/6.2.28/ubuntu/installers/foundationdb-clients_6.2.28-1_amd64.deb
  - dpkg -i foundationdb-clients_6.2.28-1_amd64.deb
  - git clone --depth 1 https://github.com/apache/couchdb

before_script:
  - cd couchdb
  - ./configure --disable-docs --disable-fauxton
  - cp -r ../!(couchdb) ./src/config
  - make

script:
  - make eunit apps=config

cache: apt
