language: erlang

otp_release:
  - 21.1
  - 20.3

env:
  - COUCHDB_BRANCH=main
  - COUCHDB_BRANCH=3.x

sudo: false

addons:
  apt:
    packages:
      - libmozjs185-dev

before_install:
  - git clone --no-single-branch --depth 1 https://github.com/apache/couchdb

before_script:
  - cd couchdb
  - git checkout origin/${COUCHDB_BRANCH}
  - ./configure --disable-docs --disable-fauxton
  - cp -r ../!(couchdb) ./src/config
  - make

script:
  - make eunit apps=config

cache: apt
